# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Corners App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: pip install -r requirements.txt
      
    - name: Set up ChromeDriver
      run: |
        wget https://github.com/LeonardoAcquaroli/corners-betting/blob/main/chromedriver.exe?raw=true
        chmod +x chromedriver.exe

    - name: Run Streamlit App
      run: streamlit run "Corners stats.py"
      env:
        CHROMEDRIVER_PATH: ./chromedriver.exe
      env:
        PYTHONUNBUFFERED: 1
